### PR TITLE
Tifffile transition

### PR DESCRIPTION
**Pull request by dlesmesl**
Changing the implementation so bigtiff is not longer required to execute the plugin

### CODE REVIEW

**Review by pranjaldhole — COMMENTED** [review]
Seems like the build fails with some `tensorflow.keras` import error.
Found a relevant issue here [https://github.com/tensorflow/models/issues/10024](https://github.com/tensorflow/models/issues/10024).

Needs to be fixed in yapic I think. Not sure whats the best way to deal with it. Perhaps hard-fixing a working version of tensorflow? @cmohl2013 what do you think?

**Comment by amgfernandes** [comment]
Perhaps check here for some potential solutions: https://github.com/keras-team/keras/issues/14632

**Comment by cmohl2013** [comment]
I saw that the build uses Tensorflow version 2.5.0. This version is currently not tested in yapic. But would be good if the version will be supported by yapic.
I added a new issue for that:
https://github.com/yapic/yapic/issues/40

**Comment by pranjaldhole** [comment]
@cmohl2013 Yeah, at the moment we're only explicitly testing for `tensorflow==2.1.0`; but we do not specify tensorflow as a requirement in yapic. Currently, let's do a work-around with explicit tensorflow dependence for `napari-yapic-prediction`. Once YAPiC is tested cross platform and we get rid of legacy `tensorflow 1.x` requirement, we can explicitly specify tensorflow in YAPiC and remove it from here.

**Pull request merged**
